"""Add release metadata and track model

Revision ID: 096b1181bc02
Revises: 7fabc5e64e64
Create Date: 2026-08-18 01:00:49.161175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096b1181bc02'
down_revision = '7fabc5e64e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('release_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_release_tracks_release_id'), ['release_id'], unique=False)

    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('other_url_label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_column('other_url_label')
        batch_op.drop_column('other_url')

    with op.batch_alter_table('release_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_release_tracks_release_id'))

    op.drop_table('release_tracks')
    # ### end Alembic commands ###
