"""Add media photo model

Revision ID: 0cf75f740a7a
Revises: ae55a99f0f70
Create Date: 2026-08-18 21:51:18.593728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf75f740a7a'
down_revision = 'ae55a99f0f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('photographer', sa.String(length=200), nullable=True),
    sa.Column('event_name', sa.String(length=200), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_photos')
    # ### end Alembic commands ###
