"""Add contact information model

Revision ID: 33016bfd5b75
Revises: 9becb5f8fbac
Create Date: 2026-08-18 22:30:01.858168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33016bfd5b75'
down_revision = '9becb5f8fbac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('general_email', sa.String(length=250), nullable=True),
    sa.Column('booking_email', sa.String(length=250), nullable=True),
    sa.Column('press_email', sa.String(length=250), nullable=True),
    sa.Column('facebook_url', sa.String(length=500), nullable=True),
    sa.Column('instagram_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('bandcamp_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_info')
    # ### end Alembic commands ###
