"""Add release credits and label information

Revision ID: 5ca13150b056
Revises: 9cb3f6a93644
Create Date: 2026-08-24 13:24:31.837445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca13150b056'
down_revision = '9cb3f6a93644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('catalog_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('format', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('lineup', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('recording_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('engineering_credit', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('mixing_mastering_credit', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('additional_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_column('additional_notes')
        batch_op.drop_column('mixing_mastering_credit')
        batch_op.drop_column('engineering_credit')
        batch_op.drop_column('recording_info')
        batch_op.drop_column('lineup')
        batch_op.drop_column('release_date')
        batch_op.drop_column('format')
        batch_op.drop_column('catalog_number')
        batch_op.drop_column('label')

    # ### end Alembic commands ###
