"""Add band member profile fields

Revision ID: 7c88a9a26132
Revises: 5ca13150b056
Create Date: 2026-08-24 22:48:05.750145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c88a9a26132'
down_revision = '5ca13150b056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('other_projects', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stage_setup', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('studio_setup', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band_members', schema=None) as batch_op:
        batch_op.drop_column('studio_setup')
        batch_op.drop_column('stage_setup')
        batch_op.drop_column('other_projects')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
