"""Add band member activity history

Revision ID: 8565a8e0b997
Revises: aff8c84533ab
Create Date: 2026-08-25 15:11:54.876777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8565a8e0b997'
down_revision = 'aff8c84533ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('band_member_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('band_member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['band_member_id'], ['band_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('band_member_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_band_member_activities_band_member_id'), ['band_member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band_member_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_band_member_activities_band_member_id'))

    op.drop_table('band_member_activities')
    # ### end Alembic commands ###
