"""Add external media photo sources

Revision ID: 873bb19d73ca
Revises: 0cf75f740a7a
Create Date: 2026-08-18 22:02:21.221097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873bb19d73ca'
down_revision = '0cf75f740a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=1000), nullable=True))
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_photos', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
