"""Add media photo source URL

Revision ID: 9becb5f8fbac
Revises: 873bb19d73ca
Create Date: 2026-08-18 22:05:30.995293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9becb5f8fbac'
down_revision = '873bb19d73ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_photos', schema=None) as batch_op:
        batch_op.drop_column('source_url')

    # ### end Alembic commands ###
