"""Add merch stock quantity

Revision ID: 9cb3f6a93644
Revises: bfb8c3eb2dbe
Create Date: 2026-08-18 23:41:38.365325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb3f6a93644'
down_revision = 'bfb8c3eb2dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merch_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merch_items', schema=None) as batch_op:
        batch_op.drop_column('stock_quantity')

    # ### end Alembic commands ###
