"""Add band member slug

Revision ID: aff8c84533ab
Revises: 7c88a9a26132
Create Date: 2026-08-25 01:01:43.506367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff8c84533ab'
down_revision = '7c88a9a26132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_band_members_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('band_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_band_members_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
